all_columns:
  - age: int
  - sex: category
  - bmi: float
  - children: category
  - smoker: category
  - region: category
  - charges: float

all_numerical_columns:
  - age
  - bmi
  - charges

all_categorical_columns:
  - sex
  - children
  - smoker
  - region

columns_to_drop:

target_column:
 - charges