data_ingestion:
 - in_file: data/insurance.csv
 - out_raw_data_path: outputs/raw_data.csv
 - out_training_data_path: outputs/training_data.csv
 - out_test_data_path: outputs/test_data.csv

data_transformation:
 - out_encoded_data: outputs/encoded_data.pkl

model_training:
 - out_trained_model: outputs/trained_model.pkl